spring:
  application:
    name: auth-service

  profiles:
    active: local

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

server:
  port: 8081

jwt:
  secret: ${JWT_SECRET}
  access-token-ttl-minutes: ${JWT_ACCESS_TTL_MINUTES:15}
  refresh-token-ttl-days: ${JWT_REFRESH_TTL_DAYS:7}
