services:
  postgres-user:
    image: postgres:16
    container_name: postgres-user
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pg_user_data:/var/lib/postgresql/data

volumes:
  pg_user_data: