spring:
  application:
    name: user-service

  profiles:
    active: local

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  data:
    cache:
      type: redis

jwt:
  secret: ${JWT_SECRET}
